Endpoints: https://fncy-testnet-seed.fncy.world
ChainId: 923018

Roothexkey: 5f4e1f061c905b0e8c5913d3683f2f3353bf2dfb0c91713d7f293d9a597b0125
Roothexaddr: "0x89E73303049EE32919903c09E8DE5629b84f59EB"

SlaveUserHexkeyFile: ./wallets/hexkey_1.csv
Hexkeyfile: ./wallets/hexkey_0.csv
UsersCreated: 10
UsersLoaded: 10
SlaveUserLoaded: 5

# contract addresses
Bep20Hex: 0x09BfDB864Fd2e650927710eFD0ed3CC70BE6401D,0x98942aB5279fFC6d16cCD35797414A8Ca8009cBA
WbnbHex: "0x7dBB75C9B8c9A781d485d8762b99eCe780818fbB"
UniswapFactoryHex: "0xEa90BF3c686A44cFba5Ebe253FAF08396B4dc78F"
UniswapRouterHex: "0x23A380Cce147125FAc6FdF5580E1bC24aEAeA4E5"
Erc721Hex: "0x5f75fdcd8d72Ca0b64750e1977C5e2F0f7E4402a"
Erc1155Hex: "0x88a156dC60F425941A39cbecB6ca3580220ABe97"

Tps: 2
Sec: 100

# set each type of scenario weights
ScenariosYml:
  SendBNB: 1
  SendBEP20: 1
  AddLiquidity: 1
  RemoveLiquidity: 1
  SwapExactTokensForTokens: 1
  SwapBNBForExactTokens: 1
  DepositWBNB: 1
  WithdrawWBNB: 1
  ERC721MintOrTransfer: 1
  ERC1155MintOrBurnOrTransfer: 1
ERC721MintOrTransferScenariosYml:
  ERC721Mint: 1
  ERC721Transfer: 9
ERC1155MintOrBurnOrTransferScenariosYml:
  ERC1155Mint: 6
  ERC1155Burn: 3
  ERC1155Transfer: 1

# distribute amount for every account, unit eth
DistributeAmountYml: 1
Erc721InitTokenNumber: 2
Erc1155InitTokenTypeNumber: 30
Erc1155InitTokenNumber: 5
