name: BNB Bridge Test

on:
  repository_dispatch:
    types: [opbnb-test]
  workflow_call:
    inputs:
      test-name:
        required: true
        type: string
      env-name:
        required: true
        type: string
      ref:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      test-name:
        description: 'chose deposit or withdraw'
        required: true
        default: 'deposit-bnb'
        type: choice
        options:
          - deposit-bnb
          - withdraw-bnb
      env-name:
        description: 'run envName'
        required: true
        default: 'opbnbtestnet'
        type: choice
        options:
          - opbnbqa
          - opbnbtestnet
          - opbnbmainnet
jobs:
  bnb-bridge-test:
    timeout-minutes: 10
    runs-on: [self-hosted, qa-infra-k8s]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: node-real/bsc-load-test
          token: ${{ secrets.GITHUB_TOKEN }}
          path: bsc-load-test
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Yarn
        run: npm install -g hardhat
      - name: Install project dependencies
        run: |
          cd bsc-load-test/func_test/uniswap_721_1155
          npm install
      - name: start BNB Bridge 
        id: bnb-bridge-test
        env:
          Test_PRIVKEY: ${{ secrets.TestPRIVKEY }}
        run: |
          echo "run: ${{ inputs.env-name }} ${{ inputs.test-name }} "
          cd bsc-load-test/func_test/uniswap_721_1155
          
          export TestENV=${{ inputs.env-name }}
          if  [[ "${{ inputs.test-name }}" = deposit-bnb ]];
          then  
              npx hardhat run --network default scripts/optimismDeposit.js 
          fi
          if [[ "${{ inputs.test-name }}" = withdraw-bnb ]];
          then
              export WithdrawOperation=justWithdraw
              npx hardhat run --network default scripts/optimismWithdrawN.js 
          fi
          echo  ${{ inputs.env-name }} ${{ inputs.test-name }} test-done
      - name: cc_warning
        id: cc-warning
        if: failure()
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.CCURL }}
          method: "POST"
          headers: '{ "app": "ccalert","Content-Type":"application/json" }'
          timeout: 5000
          body: '{ "groupID": "${{secrets.CCGroupID}}",  "msg": "-----------------------\n* ${{ inputs.env-name }} run ${{ inputs.test-name }} failure!*\n-------------------DETAILS*: \n*LINK*:  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
      - name: cc_info
        id: cc-info
        if: success()
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.CCURL }}
          method: "POST"
          headers: '{ "app": "ccalert","Content-Type":"application/json" }'
          timeout: 5000
          body: '{ "groupID": "${{secrets.CCGroupID}}",  "msg": "-----------------------\n* ${{ inputs.env-name }} run ${{ inputs.test-name }}  pass!*\n-------------------DETAILS*: \n*LINK*:  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
