name: Erc20 contract test

on:
  repository_dispatch:
    types: [opbnb-test]
  workflow_call:
    inputs:
      env-name:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      env-name:
        description: 'run envName'
        required: true
        default: 'opbnb-testnet'
        type: choice
        options:
          - opbnb-testnet
          - opbnb-mainnet
      from-address:
        description: 'from address'
        required: true
        default: '0xc5098ce789965A19A17987e02b0F789E65A21F16'
        type: choice
        options:
          - '0xc5098ce789965A19A17987e02b0F789E65A21F16'
      l2token-address:
        description: 'L2token address'
        required: true
        type: string
jobs:
  uniswap-nft-tx-test:
    timeout-minutes: 10
    runs-on: [self-hosted, qa-infra-k8s]
    env:
          github_context: '${{ toJSON(github) }}'
    steps:
      - uses: actions/checkout@v3
        with:
          repository: node-real/bsc-load-test
          token: ${{ secrets.GITHUB_TOKEN }}
          path: bsc-load-test
          ref: opbnb
      - name: start erc20 test
        id: erc20-contract-test
        env:
          Test_PRIVKEY: ${{ secrets.TestPRIVKEY }}
          RUN_ID: ${{ github.run_id }}
        run: |
          export PATH=$PATH:/usr/local/go/bin
          export L2Token=${{ inputs.l2token-address }}
          echo "run: ${{ inputs.env-name }}  erc20-contract-test "
          cd bsc-load-test/load_test/
         
          go build -o build/driver driver.go
          ./build/driver -runErc20Check -configPath=${{ inputs.env-name }}-pipeline.yml
          echo $?
      - name: cc_warning
        id: cc-warning
        if: failure()
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.CCURL }}
          method: "POST"
          headers: '{ "app": "ccalert","Content-Type":"application/json" }'
          timeout: 5000
          body: '{ "groupID": "${{secrets.CCGroupID}}",  "msg": "-----------------------\n* ${{ inputs.env-name }} run [erc20 contract test] failure!*\n-------------------DETAILS*: \n*LINK*:  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
      - name: cc_info
        id: cc-info
        if: success()
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.CCURL }}
          method: "POST"
          headers: '{ "app": "ccalert","Content-Type":"application/json" }'
          timeout: 5000
          body: '{ "groupID": "${{secrets.CCGroupID}}",  "msg": "-----------------------\n* ${{ inputs.env-name }} run [erc20 contract test] pass!*\n-------------------DETAILS*: \n*LINK*:  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
