name: ERC20 Bridge Test

on:
  repository_dispatch:
    types: [opbnb-test]
  workflow_call:
    inputs:
      test-name:
        required: true
        type: string
      env-name:
        required: true
        type: string
      ref:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      test-name:
        description: 'chose deposit or withdraw'
        required: true
        default: 'deposit-erc20'
        type: choice
        options:
          - deposit-erc20
          - withdraw-erc20
      env-name:
        description: 'run envName'
        required: true
        default: 'opbnbtestnet'
        type: choice
        options:
          - opbnbtestnet
          - opbnbmainnet
          - combomainnet
          - opbnbqa
          - opbnbfork
      from-address:
        description: 'from address'
        required: true
        default: '0xc5098ce789965A19A17987e02b0F789E65A21F16'
        type: choice
        options:
          - '0xc5098ce789965A19A17987e02b0F789E65A21F16'
          - '0x2da20a68879846E6FE30a704d776dC214943d27C'
      amount:
        description: 'amount'
        required: false
        type: string
        default: '0.001'
      l1token-address:
        description: 'L1token address'
        required: false
        type: string
        default: "0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82"
      l2token-address:
        description: 'L2token address'
        required: false
        type: string
        default: "0xd08a2917653d4e460893203471f0000826fb4034"
jobs:
  bnb-bridge-test:
    timeout-minutes: 15
    runs-on: [self-hosted, qa-infra-k8s]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: node-real/bsc-load-test
          token: ${{ secrets.GITHUB_TOKEN }}
          path: bsc-load-test
          ref: opbnb
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install hardhat
        run: npm install -g hardhat
      - name: Install project dependencies
        run: |
          cd bsc-load-test/func_test/uniswap_721_1155
          npm install
      - name: start ERC20 Bridge 
        id: erc20-bridge-test
        env:
          RUN_ID: ${{ github.run_id }}
        run: |
          echo "run: ${{ inputs.env-name }} ${{ inputs.test-name }} "
          cd bsc-load-test/func_test/uniswap_721_1155
          export TestENV=${{ inputs.env-name }}
          export AMOUNT=${{ inputs.amount }}
          export Test_PRIVKEY=${{ secrets.TestPRIVKEY }}
          if [[ "${{ inputs.env-name }}" = combomainnet ]];
          then  
              export Test_PRIVKEY=${{ secrets.ComboPRIVKEY }}
          fi
          export L1Token=${{ inputs.l1token-address }}
          export L2Token=${{ inputs.l2token-address }}
          if  [[ "${{ inputs.test-name }}" = deposit-erc20 ]];
          then  
              npx hardhat run --network default scripts/optimismDeposit20Tokens.js 
          fi
          if [[ "${{ inputs.test-name }}" = withdraw-erc20 ]];
          then
              export WithdrawOperation=justWithdraw
              npx hardhat run --network default scripts/optimismWithdraw20Tokens.js 
          fi
          echo  ${{ inputs.env-name }} ${{ inputs.test-name }} test-done
      - name: cc_warning
        id: cc-warning
        if: failure()
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.CCURL }}
          method: "POST"
          headers: '{ "app": "ccalert","Content-Type":"application/json" }'
          timeout: 5000
          body: '{ "groupID": "${{secrets.CCGroupID}}",  "msg": "-----------------------\n* ${{ inputs.env-name }} run ${{ inputs.test-name }} failure!*\n-------------------DETAILS*: \n*LINK*:  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
      - name: cc_info
        id: cc-info
        if: success()
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.CCURL }}
          method: "POST"
          headers: '{ "app": "ccalert","Content-Type":"application/json" }'
          timeout: 5000
          body: '{ "groupID": "${{secrets.CCGroupID}}",  "msg": "-----------------------\n* ${{ inputs.env-name }} run ${{ inputs.test-name }}  pass!*\n-------------------DETAILS*: \n*LINK*:  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
