name: new Uniswap and Nft tx test

on:
  repository_dispatch:
    types: [opbnb-test]
  workflow_call:
    inputs:
      env-name:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      env-name:
        description: 'run envName'
        required: true
        default: 'opbnbtestnet'
        type: choice
        options:
          - opbnb-prerelease
          - opbnb-testnet
          - opbnb-mainnet
          - combo-mainnet
jobs:
  uniswap-nft-tx-test:
    timeout-minutes: 10
    runs-on: [self-hosted, qa-infra-k8s]
    env:
          github_context: '${{ toJSON(github) }}'
    steps:
      - uses: actions/checkout@v3
        with:
          repository: node-real/bsc-load-test
          token: ${{ secrets.GITHUB_TOKEN }}
          path: bsc-load-test
      - name: start send tx
        id: uniswap-nft-tx-test
        run: |
          export PATH=$PATH:/usr/local/go/bin
          echo "run: ${{ inputs.env-name }}  uniswap-nft-tx-test "
          cd bsc-load-test/load_test/
          if [[ "${{ inputs.env-name }}" = opbnb-mainnet ]];
          then  
              sed -i 's/d3f88bafd1b5144cf128dfb0abea7fd296ba37dc60006d0ea0cf922831654c0d/${{ secrets.TestPRIVKEY }}/g' opbnb-mainnet-pipeline.yml
          fi
          if [[ "${{ inputs.env-name }}" = combo-mainnet ]];
          then  
              sed -i 's/d3f88bafd1b5144cf128dfb0abea7fd296ba37dc60006d0ea0cf922831654c0d/${{ secrets.ComboPRIVKEY }}/g' combo-mainnet-pipeline.yml
          fi
          go build -o build/driver driver.go
          ./build/driver -runSanityCheck -configPath=${{ inputs.env-name }}-pipeline.yml
          echo $?
      - name: cc_warning
        id: cc-warning
        if: failure()
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.CCURL }}
          method: "POST"
          headers: '{ "app": "ccalert","Content-Type":"application/json" }'
          timeout: 5000
          body: '{ "groupID": "${{secrets.CCGroupID}}",  "msg": "-----------------------\n* ${{ inputs.env-name }} run [uniswap&nft send transaction] failure!*\n-------------------DETAILS*: \n*LINK*:  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
      - name: cc_info
        id: cc-info
        if: success()
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.CCURL }}
          method: "POST"
          headers: '{ "app": "ccalert","Content-Type":"application/json" }'
          timeout: 5000
          body: '{ "groupID": "${{secrets.CCGroupID}}",  "msg": "-----------------------\n* ${{ inputs.env-name }} run [uniswap&nft send transaction] pass!*\n-------------------DETAILS*: \n*LINK*:  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'