name: Query Balance Test

on:
  repository_dispatch:
    types: [opbnb-test]
  workflow_call:
    inputs:
      test-name:
        required: true
        type: string
      env-name:
        required: true
        type: string
      ref:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      env-name:
        description: 'run envName'
        required: true
        default: 'opbnbtestnet'
        type: choice
        options:
          - opbnbtestnet
          - opbnbmainnet
          - combomainnet
      from-address:
        description: 'from address'
        required: true
        default: '0xc5098ce789965A19A17987e02b0F789E65A21F16'
        type: choice
        options:
          - '0xc5098ce789965A19A17987e02b0F789E65A21F16'
      l1token-address:
        description: 'L1token address'
        required: false
        type: string
      l2token-address:
        description: 'L2token address'
        required: false
        type: string
jobs:
  bnb-bridge-test:
    timeout-minutes: 15
    runs-on: [self-hosted, qa-infra-k8s]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: node-real/bsc-load-test
          token: ${{ secrets.GITHUB_TOKEN }}
          path: bsc-load-test
          ref: opbnb
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install hardhat
        run: npm install -g hardhat
      - name: Install project dependencies
        run: |
          cd bsc-load-test/func_test/uniswap_721_1155
          npm install
      - name: start query balance
        id: start-query-balance
        env:
          RUN_ID: ${{ github.run_id }}
        run: |
          echo "run: ${{ inputs.env-name }} ${{ inputs.test-name }} "
          cd bsc-load-test/func_test/uniswap_721_1155
          export TestENV=${{ inputs.env-name }}
          export L1Token=${{ inputs.l1token-address }}
          export L2Token=${{ inputs.l2token-address }}
          export Test_PRIVKEY=${{ secrets.TestPRIVKEY }}
          if [[ "${{ inputs.env-name }}" = combomainnet ]];
          then  
              export Test_PRIVKEY=${{ secrets.ComboPRIVKEY }}
          fi
          
          export WithdrawOperation=queryBalance
          npx hardhat run --network default scripts/optimismWithdraw20Tokens.js 
          
          echo  ${{ inputs.env-name }} ${{ inputs.test-name }} test-done