name: Prove_Fnalize Test

on:
  repository_dispatch:
    types: [opbnb-test]
  workflow_call:
    inputs:
      test-name:
        required: true
        type: string
      env-name:
        required: true
        type: string
      ref:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      test-name:
        description: 'chose prove or finalize'
        required: true
        default: 'prove-withdraw'
        type: choice
        options:
          - prove-withdraw
          - finalize-withdraw
      from-address:
        description: 'from address'
        required: true
        default: '0xc5098ce789965A19A17987e02b0F789E65A21F16'
        type: choice
        options:
          - '0xc5098ce789965A19A17987e02b0F789E65A21F16'
          - '0x2da20a68879846E6FE30a704d776dC214943d27C'
      env-name:
        description: 'run envName'
        required: true
        default: 'opbnbtestnet'
        type: choice
        options:
          - opbnbtestnet
          - opbnbmainnet
          - combomainnet
      withdraw-hash:
        description: 'L2 withdraw hash'
        required: true
        type: string
jobs:
  bnb-bridge-test:
    timeout-minutes: 15
    runs-on: [self-hosted, qa-infra-k8s]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: node-real/bsc-load-test
          token: ${{ secrets.GITHUB_TOKEN }}
          path: bsc-load-test
          ref: opbnb
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install hardhat
        run: npm install -g hardhat
      - name: Install project dependencies
        run: |
          cd bsc-load-test/func_test/uniswap_721_1155
          npm install
      - name: start prove or finalize 
        id: prove-finalize-test
        env:
          RUN_ID: ${{ github.run_id }}
        run: |
          echo "run: ${{ inputs.env-name }} ${{ inputs.test-name }} "
          cd bsc-load-test/func_test/uniswap_721_1155
          
          export TestENV=${{ inputs.env-name }}
          export WithdrawHash=${{ inputs.withdraw-hash }}
          export Test_PRIVKEY=${{ secrets.TestPRIVKEY }}
          if [[ "${{ inputs.env-name }}" = combo-mainnet ]];
          then  
              export Test_PRIVKEY=${{ secrets.ComboPRIVKEY }}
          fi
          if  [[ "${{ inputs.test-name }}" = prove-withdraw ]];
          then  
              export WithdrawOperation=proveWithdraw
              npx hardhat run --network default scripts/optimismWithdrawN.js 
          fi
          if [[ "${{ inputs.test-name }}" = finalize-withdraw ]];
          then
              export WithdrawOperation=finalizeWithdraw
              npx hardhat run --network default scripts/optimismWithdrawN.js 
          fi
          echo  ${{ inputs.env-name }} ${{ inputs.test-name }} test-done
      - name: cc_warning
        id: cc-warning
        if: failure()
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.CCURL }}
          method: "POST"
          headers: '{ "app": "ccalert","Content-Type":"application/json" }'
          timeout: 5000
          body: '{ "groupID": "${{secrets.CCGroupID}}",  "msg": "-----------------------\n* ${{ inputs.env-name }} run ${{ inputs.test-name }} failure!*\n-------------------DETAILS*: \n*LINK*:  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
      - name: cc_info
        id: cc-info
        if: success()
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.CCURL }}
          method: "POST"
          headers: '{ "app": "ccalert","Content-Type":"application/json" }'
          timeout: 5000
          body: '{ "groupID": "${{secrets.CCGroupID}}",  "msg": "-----------------------\n* ${{ inputs.env-name }} run ${{ inputs.test-name }}  pass!*\n-------------------DETAILS*: \n*LINK*:  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
